version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: my-custom-jenkins
    ports:
      - "9080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins_network

  chatapi:
    container_name: chat_api
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ChatDb;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - sqlserver
    networks:
      - app_network
    restart: unless-stopped

  clientehtml:
    container_name: cliente_html
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - chatapi
    restart: unless-stopped

volumes: 
  jenkins_data:
  sqlserver_data:

networks:
  jenkins_network:
    name: jenkins_network
    driver: bridge
  app_network: 
    name: app_network
    driver: bridge