version: '3.8'

services:
  chatapi:
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "5235:5235"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - chatnetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ChatApi.2025"
      ACCEPT_EULA: "Y"
    networks:
      - chatnetwork

  client:
    image: nginx:alpine
    volumes:
      - ./Client:/usr/share/nginx/html
    ports:
      - "8081:80"
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge
