version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  chatapi:
    container_name: chat_api
    build:
      context: ./ChatApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ChatDb;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - sqlserver
    restart: unless-stopped

  clientehtml:
    container_name: cliente_html_nginx
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - chatapi
    restart: unless-stopped

volumes:
  sqlserver_data: